// Generated by `pnpm gen:ipc` from crates/relay-core/src/bindings.rs.
// Do not edit: CI regenerates this file and fails on a diff.

// This file has been generated by Specta. Do not edit this file manually.
/**  The human-readable feed behind the activity slide-over (full UI is phase 4). */
export type ActivityEntry = {
	id: string,
	at: string,
	text: string,
	detail: string | null,
};

export type AuthMethod = { kind: "password" } | { kind: "keyFile"; path: string } | { kind: "agent" } | 
/**  Never stored; the user is prompted on every connect. */
{ kind: "ask" };

export type Bookmark = {
	label: string,
	remotePath: string,
};

export type ConflictAction = "overwrite" | "skip" | "keepBoth" | 
/**  Only reachable when the engine offered it: see `Prompt::Conflict::resume_allowed`. */
"resume";

export type Density = "comfortable" | "compact";

export type Direction = "up" | "down";

/**
 *  One sequenced update. `epoch` changes whenever the engine restarts, which
 *  invalidates every watermark a client is holding.
 */
export type EngineEnvelope = {
	epoch: string,
	seq: number,
	update: EngineEvent,
};

export type EngineError = 
/**  Credentials were rejected. Never carries the credential itself. */
{ kind: "auth"; message: string } | { kind: "network"; message: string } | { kind: "timeout"; operation: string; afterSecs: number } | { kind: "notFound"; path: string } | { kind: "permissionDenied"; path: string } | 
/**
 *  The user declined a host key or certificate, or a pinned key changed and the
 *  change was not accepted.
 */
{ kind: "trustRejected"; endpoint: string } | { kind: "cancelled" } | 
/**
 *  The source differs from the facts recorded when the partial transfer began.
 *  Resuming would splice two different files together.
 */
{ kind: "sourceChanged"; path: string } | 
/**
 *  Resume could not be *proven* safe. Distinct from `SourceChanged`: there we know
 *  the source moved, here we cannot establish that it did not.
 */
{ kind: "resumeUnverifiable"; reason: string } | { kind: "integrityMismatch"; expected: string; actual: string } | 
/**
 *  Local filesystem failure — a full disk, a vanished download directory, a
 *  read-only volume. Extends the taxonomy in phase 0 §0.2 because the local side
 *  fails independently of the connection and gets its own designed message.
 */
{ kind: "localIo"; path: string; message: string } | 
/**
 *  The server or backend cannot do something Relay requires for safety — notably
 *  atomic finalisation of an upload. Phase 1 fails loudly here rather than
 *  claiming a guarantee it cannot keep.
 */
{ kind: "unsupported"; operation: string } | { kind: "protocol"; message: string };

export type EngineEvent = 
/**  A tab exists. Sent before any state for that session. */
{ kind: "sessionOpened"; session: Session } | { kind: "sessionState"; id: string; state: SessionState } | { kind: "sessionClosed"; id: string } | { kind: "latency"; id: string; ms: number } | { kind: "listing"; listing: ListingSnapshot } | 
/**
 *  Covers progress and every state change; the coordinator coalesces the
 *  progress-only ones before they are sequenced.
 */
{ kind: "jobUpdate"; job: JobSnapshot } | { kind: "queueStats"; stats: QueueStats } | { kind: "log"; id: string; line: LogLine } | { kind: "activity"; id: string; entry: ActivityEntry } | { kind: "promptOpened"; prompt: PromptRequest } | { kind: "promptClosed"; id: string };

/**
 *  A consistent view of everything the UI renders. Logs are deliberately absent:
 *  they are bounded separately and fetched on demand.
 */
export type EngineSnapshot = {
	epoch: string,
	/**  Apply only buffered envelopes with a strictly greater `seq`. */
	seq: number,
	sessions: Session[],
	jobs: JobSnapshot[],
	stats: QueueStats,
	/**  Unanswered questions, so a remount reopens the sheet instead of losing it. */
	prompts: PromptRequest[],
	listings: ListingSnapshot[],
};

/**
 *  The facts a conflict or resume decision is allowed to depend on.
 * 
 *  Phase 2 requires more than a size match before resuming: `size` alone never
 *  authorises resume, which is why mtime and an optional content digest travel with it.
 */
export type FileFacts = {
	path: string,
	size: number,
	modified: string | null,
	/**  SHA-256 of the verified prefix, when one has been computed. */
	digest: string | null,
};

export type FileKind = "file" | "dir" | 
/**
 *  Symlinks carry the kind of their target so the UI can decide navigability;
 *  `None` means the target could not be stat'd (broken or permission-denied).
 */
"symlink";

/**
 *  What the queue drawer and the flow gutter render. Progress is coalesced before it
 *  reaches this type: phase 5 budgets ten updates per second per job.
 */
export type JobSnapshot = {
	id: string,
	session: string,
	serverId: string,
	direction: Direction,
	remotePath: string,
	localPath: string,
	/**  `None` while a folder job is still scanning, or when the server withholds size. */
	size: number | null,
	transferred: number,
	state: JobState,
	order: number,
	/**  Bytes per second over the recent window; `None` until there is a window. */
	speedBps: number | null,
	etaSecs: number | null,
	/**  Set once "apply to remaining" propagates a decision onto later jobs. */
	conflictPolicy: ConflictAction | null,
	/**  Folder jobs own their children; the drawer nests them under the parent. */
	parent: string | null,
	startedAt: string | null,
};

export type JobState = 
/**  Folder jobs only: enumerating children before they can be queued. */
{ kind: "scanning" } | { kind: "queued" } | 
/**  Destination stat, conflict detection, resume verification. */
{ kind: "preparing" } | { kind: "awaitingPrompt"; prompt: string } | { kind: "transferring" } | 
/**  Content is on the destination but has not been proven correct yet. */
{ kind: "verifying" } | { kind: "paused"; reason: PauseReason } | { kind: "failed"; error: EngineError; attempts: number } | { kind: "done"; at: string } | { kind: "cancelled" };

/**  A directory listing as currently known for a session's remote pane. */
export type ListingSnapshot = {
	session: string,
	path: string,
	/**
	 *  Monotonic per session. The pane ignores a listing whose request is older than
	 *  the one it is waiting for, so a slow response cannot replace a newer directory.
	 */
	request: number,
	entries: RemoteEntry[],
	at: string,
};

/**
 *  Local-pane entry. Enumerated in Rust so hidden-file rules and metadata match
 *  the remote pane on both platforms (phase 1 §1.5).
 */
export type LocalEntry = {
	name: string,
	path: string,
	kind: FileKind,
	targetKind: FileKind | null,
	size: number,
	modified: string | null,
	hidden: boolean,
	readonly: boolean,
};

export type LogKind = "status" | "command" | "response" | "error";

/**
 *  One line of the per-session protocol log. Secrets are redacted before a line is
 *  constructed, not on the way out: the phase 5 audit greps these buffers.
 */
export type LogLine = {
	at: string,
	kind: LogKind,
	line: string,
};

export type PauseReason = 
/**  A person pressed pause. */
"user" | 
/**  The session went away; the scheduler resumes these on reconnect. */
"sessionDown" | 
/**  The global concurrency limit dropped below the number of running jobs. */
"throttled";

export type Prompt = { kind: "hostKey"; host: string; algo: string; sha256: string; 
/**
 *  A pinned key for this endpoint exists and does not match. The design draws
 *  this variant in red: it is a different question, not a louder one.
 */
changed: boolean } | { kind: "tlsCert"; host: string; chainPem: string[]; sha256: string; changed: boolean } | { kind: "password"; hint: string } | { kind: "conflict"; local: FileFacts; remote: FileFacts; direction: Direction; 
/**  How many queued jobs "apply to remaining" would cover. */
remaining: number; 
/**  Resume is offered only when the engine has already verified it is safe. */
resumeAllowed: boolean };

export type PromptReply = { kind: "accept"; remember: boolean } | { kind: "deny" } | { kind: "password"; value: string } | { kind: "conflict"; action: ConflictAction; applyToRemaining: boolean };

/**
 *  A prompt as the UI sees it. Carried in `PromptOpened` and in every snapshot until
 *  it is answered.
 */
export type PromptRequest = {
	id: string,
	session: string,
	prompt: Prompt,
	openedAt: string,
};

/**
 *  Transfer protocol. Only [`Proto::Sftp`] is selectable in 1.0; the others exist so
 *  persisted configs and the FTP prototype keep their shape (ROADMAP §5).
 */
export type Proto = "sftp" | "ftps" | "ftp";

/**
 *  Queue commands the interface can issue. Phase 2 implements the scheduler behind
 *  them; phase 0 answers the ones the demo engine can honestly perform and returns
 *  `Unsupported` for the rest rather than pretending.
 */
export type QueueOp = { kind: "cancel"; job: string } | { kind: "retry"; job: string } | { kind: "pause"; job: string } | { kind: "resume"; job: string } | { kind: "pauseAll" } | { kind: "resumeAll" } | 
/**  Move `job` immediately after `after`, or to the front when `after` is `None`. */
{ kind: "reorder"; job: string; after: string | null } | { kind: "clearCompleted" };

export type QueueStats = {
	active: number,
	queued: number,
	failed: number,
	done: number,
	speedBps: number,
};

export type RemoteEntry = {
	name: string,
	kind: FileKind,
	/**  Resolved kind of a symlink target; `None` for non-symlinks and broken links. */
	targetKind: FileKind | null,
	size: number,
	modified: string | null,
	/**  Display string, e.g. `"rwxr-xr-x"`. */
	perms: string | null,
	/**  Numeric mode, kept for the post-1.0 chmod dialog. */
	mode: number | null,
	owner: string | null,
	group: string | null,
};

export type ResolveError = 
/**
 *  Already answered, timed out, or cancelled with its session. Replaying a reply
 *  after a remount lands here, and must not be treated as a failure by the UI.
 */
{ kind: "unknown" } | 
/**  The reply does not answer this kind of prompt. */
{ kind: "mismatched" };

/**  Persisted in `servers.json`. Secrets live in the OS keychain, never here. */
export type ServerConfig = {
	id: string,
	name: string,
	host: string,
	port: number,
	proto: Proto,
	username: string,
	auth: AuthMethod,
	/**  Avatar tint from the design's palette, e.g. `"#2456E6"`. */
	color: string | null,
	group: string | null,
	bookmarks?: Bookmark[],
	initialRemotePath: string | null,
};

/**
 *  What a successful connect learned about the peer. Surfaced in the session header's
 *  encryption details.
 */
export type ServerInfo = {
	banner: string | null,
	/**  e.g. `"SSH-2.0-OpenSSH_9.6"`. */
	software: string | null,
	kex: string | null,
	cipher: string | null,
	mac: string | null,
	hostKeyAlgo: string | null,
	hostKeySha256: string | null,
	/**  Directory the session landed in. */
	homePath: string,
};

export type Session = {
	id: string,
	serverId: string,
	name: string,
	proto: Proto,
	state: SessionState,
	latencyMs: number | null,
	remotePath: string | null,
};

export type SessionState = { kind: "connecting" } | { kind: "connected"; info: ServerInfo } | { kind: "reconnecting"; attempt: number; 
/**  Seconds until the next attempt, for the designed countdown. */
retryInSecs: number } | { kind: "disconnected"; reason: string; 
/**  False after a deliberate close, which suppresses the connection-lost pane. */
unexpected: boolean };

export type Settings = {
	theme: Theme,
	density: Density,
	/**  Simultaneous transfers, 1–8. */
	concurrency: number,
	/**  `None` opens the conflict sheet every time. */
	defaultConflict: ConflictAction | null,
	downloadDir: string | null,
	/**  Show dotfiles and Windows-hidden files in both panes. */
	showHidden: boolean,
};

export type SnapshotError = 
/**
 *  The subscription was dropped (overflow, unsubscribe, or engine restart).
 *  Subscribe again and retry; do not reuse the old watermark.
 */
{ kind: "unknownSubscription" };

export type Theme = "light" | "dark" | 
/**  Follow the operating system. */
"system";
