//! Regenerates `src/ipc/gen.ts`. Run it with `pnpm gen:ipc`.

use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src/ipc/gen.ts");
    let types = relay_core::bindings::type_collection();

    specta_typescript::Typescript::default()
        .header(
            "// Generated by `pnpm gen:ipc` from crates/relay-core/src/bindings.rs.\n\
             // Do not edit: CI regenerates this file and fails on a diff.\n",
        )
        .export_to(&out, &types, specta_serde::Format)?;

    println!("wrote {}", out.display());
    Ok(())
}
